apiVersion: batch/v1
kind: Job
metadata:
  name: memtier
  namespace: benchmark
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: memtier
          image: redislabs/memtier_benchmark:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-lc"]
          args:
            - |
              memtier_benchmark \
                --server=valkey.vk.svc.cluster.local \
                --port=6379 \
                --protocol=redis \
                --cluster-mode \
                --ratio=1:1 \
                --data-size=256 \
                --requests=100000 \
                --clients=50 \
                --threads=4 \
                --pipeline=1