apiVersion: v1
kind: ServiceAccount
metadata:
  name: memtier-sa
  namespace: vk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-resource-editor
  namespace: vk
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-resource-editor-binding
  namespace: vk
subjects:
- kind: ServiceAccount
  name: memtier-sa
  namespace: vk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-resource-editor
