apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"chaos-mesh.org/v1alpha1","kind":"NetworkChaos","metadata":{"annotations":{},"name":"valkey-split-brain","namespace":"vk"},"spec":{"action":"partition","direction":"both","duration":"90s","mode":"all","selector":{"labelSelectors":{"app.kubernetes.io/instance":"valkey","app.kubernetes.io/name":"valkey","chaos-side":"minority"},"namespaces":["vk"]},"target":{"mode":"all","selector":{"labelSelectors":{"app.kubernetes.io/instance":"valkey","app.kubernetes.io/name":"valkey","chaos-side":"majority"},"namespaces":["vk"]}}}}
  creationTimestamp: "2026-06-05T07:46:03Z"
  finalizers:
  - chaos-mesh/records
  generation: 18
  name: valkey-split-brain
  namespace: vk
  resourceVersion: "1780645653613983024"
  uid: f52169e1-ac81-4e96-b026-71990fa14961
spec:
  action: partition
  direction: both
  duration: 90s
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/instance: valkey
      app.kubernetes.io/name: valkey
      chaos-side: minority
    namespaces:
    - vk
  target:
    mode: all
    selector:
      labelSelectors:
        app.kubernetes.io/instance: valkey
        app.kubernetes.io/name: valkey
        chaos-side: majority
      namespaces:
      - vk
status:
  conditions:
  - status: "False"
    type: AllInjected
  - status: "True"
    type: AllRecovered
  - status: "False"
    type: Paused
  - status: "True"
    type: Selected
  experiment:
    containerRecords:
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:04Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-4
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:04Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-0
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .Target
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:04Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-3
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .Target
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:04Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-2
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .Target
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:04Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-1
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .Target
    - events:
      - operation: Apply
        timestamp: "2026-06-05T07:46:05Z"
        type: Succeeded
      - operation: Recover
        timestamp: "2026-06-05T07:47:33Z"
        type: Succeeded
      id: vk/valkey-5
      injectedCount: 1
      phase: Not Injected
      recoveredCount: 1
      selectorKey: .Target
    desiredPhase: Stop
  instances:
    vk/valkey-0: 8
    vk/valkey-1: 8
    vk/valkey-2: 8
    vk/valkey-3: 8
    vk/valkey-4: 8
    vk/valkey-5: 8
