apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: valkey-kill-all
  namespace: vk
spec:
  selector:
    namespaces:
      - vk
    labelSelectors:
      app.kubernetes.io/instance: valkey
  mode: all
  action: pod-kill
  gracePeriod: 1
