apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  duration: "90s"
  selector:
    namespaces:
      - vk
    labelSelectors:
      statefulset.kubernetes.io/pod-name: valkey-1