apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: split-brain-valkey-1-minority
  namespace: chaos-mesh
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - vk
    labelSelectors:
      chaos-side: minority
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - vk
      labelSelectors:
        chaos-side: majority