image:
  tag: "9.1.0"

cluster:
  enabled: true
  shards: 3
  replicasPerShard: 1
  persistence:
    size: 15Gi

resources:
  requests:
    cpu: "2"
    memory: "7Gi"
  limits:
    cpu: "2"
    memory: "7Gi"

valkeyConfig: |
  maxmemory 5200mb
  maxmemory-policy allkeys-lru
  maxmemory-clients 7%
  maxclients 16000
  cluster-preferred-endpoint-type ip


metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    extraLabels:
      release: monitoring
