image:
  tag: "9.1.0"

cluster:
  enabled: true
  shards: 3
  replicasPerShard: 1
  persistence:
    size: 5Gi

valkeyConfig: |
  maxmemory 1gb
  maxmemory-policy allkeys-lru
  cluster-preferred-endpoint-type ip

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    extraLabels:
      release: monitoring
