global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/redis-cluster
  tag: 7.2.5-debian-12-r4

usePassword: false

cluster:
  init: true
  nodes: 6
  replicas: 1

persistence:
  enabled: true
  size: 5Gi

redis:
  useAOFPersistence: "no"
  startupProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 36
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 6
    failureThreshold: 12
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 18
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  configmap: |-
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    cluster-preferred-endpoint-type ip
    save ""
    appendonly no
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 512mb 128mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    labels:
      release: monitoring
