apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: statsd-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: statsd-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      interval: 5s
      path: /metrics